
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POST = 9;
  public static final int SEMICOLON = 18;
  public static final int RBRACE = 20;
  public static final int TEST = 6;
  public static final int STATUS = 13;
  public static final int IN = 16;
  public static final int EXPECT = 12;
  public static final int IDENTIFIER = 23;
  public static final int COLON = 22;
  public static final int LBRACE = 19;
  public static final int PUT = 10;
  public static final int CONTAINS = 15;
  public static final int STRING = 24;
  public static final int EQUALS = 17;
  public static final int DESCRIPTION = 7;
  public static final int NUMBER = 26;
  public static final int EOF = 0;
  public static final int DOTDOT = 21;
  public static final int error = 1;
  public static final int LET = 5;
  public static final int MULTILINE_STRING = 25;
  public static final int BODY = 14;
  public static final int HEADER = 4;
  public static final int BASE_URL = 3;
  public static final int DELETE = 11;
  public static final int CONFIG = 2;
  public static final int GET = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONFIG",
  "BASE_URL",
  "HEADER",
  "LET",
  "TEST",
  "DESCRIPTION",
  "GET",
  "POST",
  "PUT",
  "DELETE",
  "EXPECT",
  "STATUS",
  "BODY",
  "CONTAINS",
  "IN",
  "EQUALS",
  "SEMICOLON",
  "LBRACE",
  "RBRACE",
  "DOTDOT",
  "COLON",
  "IDENTIFIER",
  "STRING",
  "MULTILINE_STRING",
  "NUMBER"
  };
}

